# Generated by Django 3.2.6 on 2022-08-27 12:40

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(auto_created=True, max_length=50, unique=True)),
                ('cloudinaryfile', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cloudinaryfile',
                'verbose_name_plural': 'cloudinaryfiles',
            },
        ),
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'postSection',
                'verbose_name_plural': 'postSections',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='categorias',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cloudinaryfiletest',
            field=models.ImageField(blank=True, upload_to='test/'),
        ),
        migrations.AddField(
            model_name='post',
            name='cloudinaryimg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(choices=[('Electrónica', 'Electrónica'), ('Desarrollo Web', 'Desarrollo Web'), ('DataScience & IA', 'DataScience & IA'), ('Impresión 3D', 'Impresión 3D'), ('Otros Posts', 'Otros Posts')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CloudinaryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('cloudinaryfiles', models.ManyToManyField(blank=True, to='blog.CloudinaryFile')),
                ('name2', models.ManyToManyField(to='blog.Subcategoria')),
                ('relatedpost', models.ManyToManyField(to='blog.Post')),
            ],
            options={
                'verbose_name': 'cloudinaryMedia',
                'verbose_name_plural': 'cloudinaryMedias',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subcategoriaprincial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subcategoria', to='blog.subcategoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='subcategorias',
            field=models.ManyToManyField(to='blog.Subcategoria'),
        ),
    ]
