# Generated by Django 3.2.6 on 2022-08-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220827_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsection',
            old_name='name',
            new_name='title',
        ),
    ]
