# Generated by Django 3.2.6 on 2022-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_name_postsection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postSections',
            field=models.ManyToManyField(blank=True, to='blog.PostSection'),
        ),
    ]
