# Generated by Django 3.2.6 on 2022-09-04 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_postsections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postSections',
        ),
        migrations.AddField(
            model_name='post',
            name='postSections',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postsection'),
            preserve_default=False,
        ),
    ]
