# Generated by Django 3.2.6 on 2022-09-04 19:18

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220904_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinarymedia',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsection',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsection',
            name='cloudinaryimg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postSections',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.postsection'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategoriaprincial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Subcategoria', to='blog.subcategoria'),
        ),
    ]
