# Generated by Django 3.2.6 on 2022-09-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220904_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cloudinaryfiletest',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postSections',
        ),
        migrations.AddField(
            model_name='postsection',
            name='relatedPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='postsection',
            name='sectionTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
