# Generated by Django 3.2.6 on 2022-09-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220904_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AlterField(
            model_name='postsection',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
