# Generated by Django 3.2.6 on 2022-09-04 22:15

import ckeditor.fields
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220904_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsection',
            old_name='body',
            new_name='body1',
        ),
        migrations.RenameField(
            model_name='postsection',
            old_name='cloudinaryimg',
            new_name='cloudinaryimg1',
        ),
        migrations.AddField(
            model_name='postsection',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsection',
            name='body3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsection',
            name='body4',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsection',
            name='body5',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsection',
            name='cloudinaryimg2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='postsection',
            name='cloudinaryimg3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='postsection',
            name='cloudinaryimg4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='postsection',
            name='cloudinaryimg5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
