# Generated by Django 3.2.6 on 2021-11-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_cloudinaryimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
