# Generated by Django 3.2.6 on 2022-09-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220905_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceCategoryName', models.CharField(auto_created=True, max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DeviceCategory',
                'verbose_name_plural': 'DeviceCategories',
            },
        ),
        migrations.CreateModel(
            name='ElectronicComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50, unique=True)),
                ('deviceType', models.CharField(choices=[('Sensores', 'Sensores'), ('Actuadores', 'Actuadores'), ('Componentes', 'Componentes')], max_length=50, unique=True)),
                ('deviceDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('deviceCategories', models.ManyToManyField(to='blog.Subcategoria')),
            ],
            options={
                'verbose_name': 'ElectronicComponent',
                'verbose_name_plural': 'ElectronicComponents',
            },
        ),
    ]
