# Generated by Django 3.2.6 on 2021-12-07 11:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('cloudinaryfile', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
            ],
            options={
                'verbose_name': 'cloudinaryMedia',
                'verbose_name_plural': 'cloudinaryMedias',
            },
        ),
    ]
