# Generated by Django 3.2.6 on 2021-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_cloudinarymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinarymedia',
            name='relatedpost',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
