# Generated by Django 3.2.6 on 2022-09-04 23:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_electroniccomponent_devicecategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroniccomponent',
            name='cloudinaryimg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='electroniccomponent',
            name='deviceType',
            field=models.CharField(choices=[('Sensores', 'Sensores'), ('Actuadores', 'Actuadores'), ('Componentes', 'Componentes'), ('Microcontroladores', 'Microcontroladores')], max_length=50, unique=True),
        ),
    ]
