# Generated by Django 3.2.6 on 2022-09-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220905_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electroniccomponent',
            name='deviceType',
            field=models.CharField(choices=[('Sensores', 'Sensores'), ('Actuadores', 'Actuadores'), ('Componentes', 'Componentes'), ('Microcontroladores', 'Microcontroladores')], max_length=50),
        ),
    ]
