# Generated by Django 3.2.6 on 2021-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_cloudinarymedia_relatedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinarymedia',
            name='cloudinaryfiletest',
            field=models.ImageField(blank=True, upload_to='test/'),
        ),
    ]
