# Generated by Django 3.2.6 on 2021-12-13 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_cloudinarymedia_cloudinaryfiletest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinarymedia',
            name='cloudinaryfile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image/test'),
        ),
    ]
