# Generated by Django 3.2.6 on 2021-12-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_cloudinarymedia_cloudinaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinarymedia',
            name='cloudinaryfiletest',
            field=models.ImageField(blank=True, upload_to='https://api.cloudinary.com/v1_1/dpc0ldfnt/mh/upload'),
        ),
    ]
