# Generated by Django 3.2.6 on 2021-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_cloudinarymedia_cloudinaryfiletest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cloudinaryfiletest',
            field=models.ImageField(blank=True, upload_to='https://api.cloudinary.com/v1_1/dpc0ldfnt/mh/upload'),
        ),
    ]
