# Generated by Django 3.2.6 on 2024-04-16 00:44

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_electronic_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSectionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cloudinaryimg', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'postSectionElement',
                'verbose_name_plural': 'postSectionElements',
            },
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='body1',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='body4',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='body5',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='cloudinaryimg1',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='cloudinaryimg2',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='cloudinaryimg3',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='cloudinaryimg4',
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='cloudinaryimg5',
        ),
        migrations.AddField(
            model_name='postsection',
            name='postSectionElements',
            field=models.ManyToManyField(to='blog.PostSectionElement'),
        ),
    ]
