# Generated by Django 3.2.6 on 2024-04-16 00:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20240416_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsectionelement',
            name='cloudinaryimg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
