# Generated by Django 3.2.6 on 2021-12-20 14:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20211220_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cloudinaryimg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
