# Generated by Django 3.2.6 on 2024-04-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_postsectionelement_cloudinaryimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsection',
            name='postSectionElements',
        ),
        migrations.AddField(
            model_name='postsection',
            name='postSectionElements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postsectionelement'),
        ),
    ]
