# Generated by Django 3.2.6 on 2021-12-20 18:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_cloudinaryimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinaryfile', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cloudinaryfile',
                'verbose_name_plural': 'cloudinaryfiles',
            },
        ),
        migrations.RemoveField(
            model_name='cloudinarymedia',
            name='cloudinaryfile',
        ),
        migrations.RemoveField(
            model_name='cloudinarymedia',
            name='cloudinaryfiletest',
        ),
        migrations.AddField(
            model_name='cloudinarymedia',
            name='cloudinaryfiles',
            field=models.ManyToManyField(blank=True, to='blog.CloudinaryFile'),
        ),
    ]
