# Generated by Django 3.2.6 on 2024-04-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20240416_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsection',
            name='postSectionElements',
        ),
        migrations.AddField(
            model_name='postsection',
            name='postSectionElements',
            field=models.ManyToManyField(blank=True, null=True, to='blog.PostSectionElement'),
        ),
    ]
