# Generated by Django 3.2.6 on 2021-12-20 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20211220_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinaryfile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
