# Generated by Django 3.2.6 on 2024-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20240416_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsection',
            name='postSectionElements',
            field=models.ManyToManyField(blank=True, to='blog.PostSectionElement'),
        ),
    ]
