# Generated by Django 3.2.6 on 2021-12-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_cloudinaryfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinarymedia',
            name='name2',
            field=models.ManyToManyField(to='blog.Subcategoria'),
        ),
    ]
