# Generated by Django 3.2.6 on 2021-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_cloudinarymedia_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryfile',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
